/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CreateRouteImport } from './routes/create'
import { Route as EventIdRouteImport } from './routes/$eventId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManageEventIdRouteImport } from './routes/manage/$eventId'
import { Route as EditEventIdRouteImport } from './routes/edit/$eventId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdRoute = EventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageEventIdRoute = ManageEventIdRouteImport.update({
  id: '/manage/$eventId',
  path: '/manage/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const EditEventIdRoute = EditEventIdRouteImport.update({
  id: '/edit/$eventId',
  path: '/edit/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$eventId': typeof EventIdRoute
  '/create': typeof CreateRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/edit/$eventId': typeof EditEventIdRoute
  '/manage/$eventId': typeof ManageEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$eventId': typeof EventIdRoute
  '/create': typeof CreateRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/edit/$eventId': typeof EditEventIdRoute
  '/manage/$eventId': typeof ManageEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$eventId': typeof EventIdRoute
  '/create': typeof CreateRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/edit/$eventId': typeof EditEventIdRoute
  '/manage/$eventId': typeof ManageEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$eventId'
    | '/create'
    | '/events'
    | '/login'
    | '/profile'
    | '/signup'
    | '/edit/$eventId'
    | '/manage/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$eventId'
    | '/create'
    | '/events'
    | '/login'
    | '/profile'
    | '/signup'
    | '/edit/$eventId'
    | '/manage/$eventId'
  id:
    | '__root__'
    | '/'
    | '/$eventId'
    | '/create'
    | '/events'
    | '/login'
    | '/profile'
    | '/signup'
    | '/edit/$eventId'
    | '/manage/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventIdRoute: typeof EventIdRoute
  CreateRoute: typeof CreateRoute
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  EditEventIdRoute: typeof EditEventIdRoute
  ManageEventIdRoute: typeof ManageEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$eventId': {
      id: '/$eventId'
      path: '/$eventId'
      fullPath: '/$eventId'
      preLoaderRoute: typeof EventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/$eventId': {
      id: '/manage/$eventId'
      path: '/manage/$eventId'
      fullPath: '/manage/$eventId'
      preLoaderRoute: typeof ManageEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$eventId': {
      id: '/edit/$eventId'
      path: '/edit/$eventId'
      fullPath: '/edit/$eventId'
      preLoaderRoute: typeof EditEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventIdRoute: EventIdRoute,
  CreateRoute: CreateRoute,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  EditEventIdRoute: EditEventIdRoute,
  ManageEventIdRoute: ManageEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
